baseurl = "https://tmail.dpp.st"
languageCode = "fr-fr"
title = "tmail"
Paginate = "10"

[Author]
	name = "Stéphane Depierrepont"
	googleAuthorship = "+St%C3%A9phaneDepierrepont"

[Params]
	Description = "Journal de développement d'un serveur SMTP"
	DefaultKeywords = ["tmail", "smtp", "develloppement", "golang"]
	DisqusShortname = "tmail"

[Taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"	
