baseurl = "http://tmail.io"
languageCode = "fr-fr"
title = "tmail"

[Params]
	Description = "devblog"
	Author = "Stephane Depierrepont aka toorop"
	disqusShortname = "tmail"

[Taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"	
